// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjCWYa88xfojpCRvTFKJRS1hOJxLMHLIM',
    appId: '1:117630969159:web:a3cf4f10e919e458fa9862',
    messagingSenderId: '117630969159',
    projectId: 'testappwithhive',
    authDomain: 'testappwithhive.firebaseapp.com',
    storageBucket: 'testappwithhive.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOcmVik5prqx9X9Q6vJ7GXXxnF4tQguxM',
    appId: '1:117630969159:android:4657225c14570b21fa9862',
    messagingSenderId: '117630969159',
    projectId: 'testappwithhive',
    storageBucket: 'testappwithhive.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArZzqoIxxwbQXlRqLZn8h2siU2TRrDVBA',
    appId: '1:117630969159:ios:bb1dcece2a384a56fa9862',
    messagingSenderId: '117630969159',
    projectId: 'testappwithhive',
    storageBucket: 'testappwithhive.appspot.com',
    iosClientId: '117630969159-oc35aenenolcmfld65v44h0aqhrojau5.apps.googleusercontent.com',
    iosBundleId: 'com.example.testappwithhive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArZzqoIxxwbQXlRqLZn8h2siU2TRrDVBA',
    appId: '1:117630969159:ios:bb1dcece2a384a56fa9862',
    messagingSenderId: '117630969159',
    projectId: 'testappwithhive',
    storageBucket: 'testappwithhive.appspot.com',
    iosClientId: '117630969159-oc35aenenolcmfld65v44h0aqhrojau5.apps.googleusercontent.com',
    iosBundleId: 'com.example.testappwithhive',
  );
}
